Fix compilation errors, caused by NULL-checks on a C++ reference.
GCC 6.3 is giving errors like this:

error: the compiler can assume that the address of ‘cter’ will never be NULL [-Werror=address]

I haven't gone through all the code to check if any of the callers might
try to pass a NULL, but I've been running with this patch on my laptop for
quite a long time and haven't seen any issues. All the tests pass.